### ISSUE TITLE
建议给依赖cloud-ui.vusion的版本设一个上限

### ISSUE THREAD

**Issue by HEIBAIJIE** [vusion-templates/admin-cloud-fs#2]
在cloud-ui.vusion@0.4.2 下能正常跑
但是最新的 cloud-ui.vusion@0.4.8 跑起来会报错
原因是\client\views\中三个页面都用到了
import 'cloud-ui.vusion/dist/theme-dark.css'
但是最新版cloud-ui.vusion已经没有这个文件和相关资源了

**Comment by z-ZYS-s** [comment]
谢谢建议！
这个非常抱歉，admin-cloud-fs 下的配置 "cloud-ui.vusion": "^0.4.2" 表示更新到 0.4.x 的最新版，本身没有问题，新版往往会修复一些小 bug。
这里是我们发包的问题，dist 目录里的这块内容没有处理好。cloud-ui.vusion@0.4.8 应该要兼容 cloud-ui.vusion@0.4.2。
以后会更加注意发包流程。

你可以先锁定 "cloud-ui.vusion": "0.4.2" 版本用着。

**Comment by z-ZYS-s** [comment]
可以了解一下你是部门的哪位同事吗？

**Comment by HEIBAIJIE** [comment]
> 可以了解一下你是部门的哪位同事吗？

小程序小组，朱齐越
